# -*- coding: utf-8 -*-
"""Day 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6VvYXnkLNoXhoMsLn1T7Ic49z1yiyQk

# Two sum problem
"""

class Solution(object):
    def twoSum(self, nums, target):
        my_dict = {}

        for i in range(len(nums)):
            number = target - nums[i]
            if number in my_dict:
                return [my_dict[number], i]
            my_dict[nums[i]] = i
        return []

# EXAMPLE
a=Solution()
a.twoSum([2,7,11,15],9)

"""steps
1. Make a new dictionary and store the key value pair
2. Make a new varaiable and store the difference of target and fetched number and store the index as key and value as value
3. In every loop check weather the number stored in the variable is known or not
4. If the number is found in the dict then print that number value key and latest value of i
5. Now your question is solved

# 2 Remove duplicates from sorted array
"""

class Solution(object):
    def removeDuplicates(self, nums):

        i = 0
        for j in range(1, len(nums)):
            if nums[j] != nums[i]:
                i += 1
                nums[i] = nums[j]

        return i + 1

"""steps
1. first of all we have to initialize i as 0th element and j as first element
2. then we need to check weather the no is unique or not
3. if the number is unique then we update i and replace the unique number with the ith element
4. if all the elements are traversed then we return the i+1
5. your question is solved
"""
# EXAMPLE
b=Solution()
b.removeDuplicates([1,1,2])

"""# 3 Remove Element"""

class Solution(object):
    def removeElement(self, nums, val):
        k = 0
        for i in range(len(nums)):
            if nums[i] != val:
                nums[k] = nums[i]
                k += 1
        return k
# EXAMPLE
c =Solution()
c.removeElement([3,2,2,3],3)

"""steps
1. first we need to initialize a variable as k=0
2. now we need to make a loop so that we can find the numbers rather that given numbers
3. if the number is not the removing element then we will replace its position with the ith number and replace the removing number
4. update the k  and after the execution return the k
5. Your question is solved
"""
